### ISSUE TITLE
Integration with Bloodmoon

### ISSUE THREAD

**Issue by aMerryElk** [zlainsama/PeacefulSurface#10]
It would be brilliant if there was integration with the mod [Bloodmoon](https://github.com/lumien231/Bloodmoon/blob/master/src/main/java/lumien/bloodmoon/server/BloodmoonHandler.java#L143). A "ActiveUnderBloodmoon" tag for rules, so that we can allow monsters to spawn on the surface only under a bloodmoon would be perfect.

**Comment by zlainsama** [comment]
I will try to add this in 1.10 and 1.11

**Comment by zlainsama** [comment]
The feature has been added with version 1.10.2-v3 and 1.11-v2
Check the wiki if you need further explanation

**Comment by aMerryElk** [comment]
Thank you a lot! ^ ^
