### ISSUE TITLE
Bloodmoon support for 1.7.10?

### ISSUE THREAD

**Issue by Kiefy** [zlainsama/PeacefulSurface#13]
Please add for 1.7 too.  It is very much still alive!

**Comment by zlainsama** [comment]
The Bloodmoon mod, this mod add support for, is not available for 1.7.10.
You will need to tell me what mod you want me to add support for.

**Comment by Kiefy** [comment]
Oh, sorry. I didn't realise it was a different mod in later versions.

I believe it is [Random Things](https://minecraft.curseforge.com/projects/random-things/files/2216390) which adds the Bloodmoon event.

**Comment by zlainsama** [comment]
A new version (1.7.x-v8) has been released.
There might be some delay since Curse needs to check the file first for it to show up.

**Comment by Kiefy** [comment]
Amazing. Thank You!
