### ISSUE TITLE
Moon phase doesn't work

### ISSUE THREAD

**Issue by ghost** [zlainsama/PeacefulSurface#14]
{
  "Disabled": false,
  "Living": false,
  "Mob": true,
  "Animal": false,
  "Tameable": false,
  "Checking_LightLevel": false,
  "Raining": false,
  "Thundering": false,
  "Day": false,
  "Night": false,
  "InvertedMobFilter": false,
  "InvertedDimensionFilter": false,
  "InvertedLightLevelChecking": false,
  "mobFilter": "(\\bSlime\\b)",
  "dimensionFilter": "(\\bThe End\\b)|(\\bNether\\b)",
  "LightLevel": 0,
  "MoonPhase": 5,
  "DisabledUnderBloodmoon": false
}
Mobs spawns based on vanilla mechanic every moon phase

**Comment by zlainsama** [comment]
Is the world modded? like BiomesOPlenty's overworld.
Is it Overworld?

**Comment by wsceo** [comment]
It's overworld default generation.

**Comment by zlainsama** [comment]
By the look of your rule, it appears there is no check applied in the rule.
It means even if the rule is active in the MoonPhase 5, nothing will change.
You need to at least put a check option on. (Checking_LightLevel & LightLevel; Raining; Thundering; Day; Night; these are check options. They decide if the mob should be denied from spawning.)
If you want to make it "MoonPhase 5 will not spawn any mobs", you should set "Checking_LightLevel" to "true" and set "LightLevel" to "-1".
