### ISSUE TITLE
Mobs ignore Rules when Dynamic Trees are Installed

### ISSUE THREAD

**Issue by Shazuli** [zlainsama/PeacefulSurface#15]
***Hi***

Just got your mod installed, but right away I noticed that mobs continue spawning in forests. I have a few mods installed so it wasn't hard to find the culprit who did this, and it looks like was is [Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees) by the process of elimination. The lightlevel under the trees seem to always be above `0`, and if there were any I missed it wouldn't explain the crowd of mobs I could find.
I also tried messing with the `DefaultRule.json` file, but nothing seem to keep the mobs from not spawning. And deleting it and going on the default values didn't do anything either.

*Forge* : *14.23.5.2789*
*Peaceful Surface* : *1.12.2-v1*
*Dynamic Trees* : *1.12.2-0.7.8*

**Comment by zlainsama** [comment]
Could you try to place and remove a torch in those forests to update their light value on server side? to see if that cause the issue disappear.
Sometimes when terrain is generating, especially with structures like trees, those areas' light level are not correct/updated on server side.

**Comment by zlainsama** [comment]
BTW, I tried dynamic trees in my local server before, it was an interesting concept, but it takes too much resources, i removed it later.

**Comment by Shazuli** [comment]
Hmm. Tried your idea with the torch but they keep on spawning still (I tried it on a bunch of different places).

![2018-12-20_20 11 05](https://user-images.githubusercontent.com/9884180/50305560-75870f80-0493-11e9-9478-b9c5ea6f4668.png)


I'm running on client ATM. But if its demanding on a server I might skip it in that case.

**Comment by zlainsama** [comment]
Hmm, I just tried it myself, confirmed they keep on spawning.
It's like those leaves and branches are solid on server side, so sky light couldn't reach under those trees.

**Comment by zlainsama** [comment]
Light level in minecraft is a combined value of sky light and block light.
Torches are block light, sky light is provided by the sky (different value during a day/night cycle) and it will be reduced by solid blocks above.

At night, mobs don't spawn when there are no dynamic trees to shade the area.
And with a torch present under those trees, makes mobs don't spawn in those areas.
This indicates peaceful surface is working correctly.

If you want this issue be fixed, you should report this to dynamic trees' author.

**Comment by zlainsama** [comment]
You can make a superflat world, make it night, use command '/kill @e[type=!Player]' constantly or use a command block to repeat it for you.
This will kill anything that isn't a player, with this and peaceful surface installed, you can demonstrate this issue to dynamic trees' author.

**Comment by Shazuli** [comment]
Alright, thanks for the help! I'll close this issue in that case.
