### ISSUE TITLE
Combine rules for more permissive spawning?

### ISSUE THREAD

**Issue by Derpford** [zlainsama/PeacefulSurface#16]
Right now, if you specify two spawn conditions--let's say, raining = true *and* lightlevel filtering--the mobs will only spawn if they match both filters.

Would it be possible to set up a filter that enables spawns in the dark *and* enables spawns everywhere when it rains?

**Comment by zlainsama** [comment]
You can use multiple rule files as long as they are placed inside the rules folder.
There is also a command("/reloadpeace") to reload these rules on the fly.

A filter that enables spawns in the dark and enables spawns everywhere when it rains means disable spawns when it's sunny and not in the dark.
Hmm, there is no condition for when it's sunny, I might need to add that.

**Comment by Derpford** [comment]
But if I have one rule file that enables spawns in the dark, and another
which enables spawns when it's raining, does that mean that spawns are
enabled if it's dark *or* raining, or does that mean that spawns are
disabled unless it's raining *and* it's dark?

**Comment by zlainsama** [comment]
The rules are working in a denying nature, you specify what does not spawn under certain conditions.
You will need a rule that disables spawns when it's sunny and not dark enough.
Currently, there is no condition available for when it's sunny, I will add it soon.
Sorry about the inconvenience.

**Comment by Derpford** [comment]
I don't think you understand, I want spawning to happen in the dark
only,and then *if it's raining* I want to enable spawning everywhere.

**Comment by zlainsama** [comment]
Yeah... I understand now, after looking into my code, I know the problem now.
I will add pre-conditions that will disable the rule.
