### ISSUE TITLE
Config Questions

### ISSUE THREAD

**Issue by YOYOK9** [zlainsama/PeacefulSurface#18]
Just some question about the configs. With the dimensionFilters is it safe to assume that the \\bthe_end\\b is blacklist where \\wthe_end\\w would be whitelist? I would like to add extra utilities deep dark to the list for mob removal. they are hard on our server.

**Comment by zlainsama** [comment]
You can search for some tutorials about regular expressions, there are also some useful online editor tools for you to play around.
