### ISSUE TITLE
Regular question to change Spawning

### ISSUE THREAD

**Issue by DerHofnarr** [zlainsama/PeacefulSurface#19]
Hi! First of all great mod a lot of potential!!

I just have a regular question: how can i enable mob spawning with a SKY LIGHT LEVEL of 15 and a BLOCK LIGHT LEVEL of >5 (overworld night). Tried in the config setting the Light Level to 5 but i found out that i need to tell the mod that tha sky level is 15, because i checked if mobs can spawn in caves. 

Just to give you a little back story: im currently playing with Minecolonies and i just want Mobs to stop spawning in my city but allow them to spawn outside without placing torches everywhere. To make it a bit realistic you know? ;-)

I would be thankfull for a helpfull answer. 

Cheers ~ Hofnarr

**Comment by zlainsama** [comment]
If I remembered correctly, my mod currently can only check combined(sky & block) light level, it can't treat them separately.

If you want no mobs spawning in a defined area, a mob stopping mod or land claiming plugin might be better at this.

**Comment by DerHofnarr** [comment]
ah ok thank you really much for your answer. :-)
