### ISSUE TITLE
I have a question about making rules

### ISSUE THREAD

**Issue by JadianRadiator** [zlainsama/PeacefulSurface#20]
Since there's a "config\PeacefulSurface_Rules\DefaultRule.json" file,
I assume I can write new .json files to create rules.
Am I correct?
And if I am, anything I should know before naming my rules' json file(s)?

**Comment by zlainsama** [comment]
Yes, you can have multiple .json files and all of them will be loaded into the game.
There is no naming restriction/requirement, as long as they are .json files, they will be loaded.
