### ISSUE TITLE
Combining Rules

### ISSUE THREAD

**Issue by wildstoats** [zlainsama/PeacefulSurface#21]
Is it possible to combine rules that would otherwise conflict?  For example I am trying to accomplish the following:
* Disable all hostile mobs in overworld, leaving nether and end as default
* Except: allow normal spawning rules in swamps
* Except: allow pillager patrols and outposts to spawn as default

I know this sort of thing is possible with InControl but your mod is the closest thing I've found that's available for Fabric.  Any help would be most appreciated.

**Comment by zlainsama** [comment]
Something like this should be able to accomplish your first two goals.
I'm not sure if pillager spawns are affected by my mod.

```json
{
  "Disabled": false,
  "Living": false,
  "Monster": true,
  "Animal": false,
  "UseMobFilter": false,
  "UseDimensionFilter": true,
  "UseBiomeFilter": true,
  "Checking_LightLevel": true,
  "Checking_Altitude": false,
  "Sunny": false,
  "Raining": false,
  "Thundering": false,
  "Day": false,
  "Night": false,
  "InvertedMobFilter": false,
  "InvertedDimensionFilter": false,
  "InvertedBiomeFilter": false,
  "InvertedLightLevelChecking": false,
  "InvertedAltitudeChecking": false,
  "mobFilter": "(\\bminecraft:slime\\b)",
  "dimensionFilter": "(\\bminecraft:the_end\\b)|(\\bminecraft:the_nether\\b)",
  "biomeFilter": "(\\bminecraft:swamp\\b)",
  "LightLevel": -1,
  "Altitude": 60,
  "MoonPhase": 0,
  "DisabledUnderBloodmoon": false,
  "DisabledWhenSunny": false,
  "DisabledWhenRaining": false,
  "DisabledWhenThundering": false,
  "DisabledWhenDay": false,
  "DisabledWhenNight": false
}
```

You can also use multiple json files to define multiple rules as long as they are in side the rules folder.

**Comment by wildstoats** [comment]
Thanks for the quick response, this has answered my question.  Cheers.
