### ISSUE TITLE
Enhanced Celestials blood moon filter not working

### ISSUE THREAD

**Issue by Strubbelkopp** [zlainsama/PeacefulSurface#31]
Enhanced Celestials has been made data driven recently, which makes the 'DisabledUnderBloodmoon' filter not work.
To fix that you could  maybe get the current lunar event from [getLunarEventKey](https://github.com/CorgiTaco/Enhanced-Celestials/blob/1.19.X/Common/src/main/java/corgitaco/enhancedcelestials/lunarevent/LunarEventInstance.java) and check if that is of the [blood moon tag](https://github.com/CorgiTaco/Enhanced-Celestials/blob/1.19.X/Common/src/main/java/corgitaco/enhancedcelestials/api/ECLunarEventTags.java)

**Comment by PixelatedBruh** [comment]
The issue has returned
