### ISSUE TITLE
I'm having trouble configuring PeacefulSurface

### ISSUE THREAD

**Issue by JadianRadiator** [zlainsama/PeacefulSurface#36]
I'm having trouble configuring PeacefulSurface.
Both the configuration wiki and config file itself don't tell you which options do what.
And the configuration wiki tells you less then the config file.
You haven't actually posted how to set which options to do what for mob spawning.
It feels as if you considered it so intuitive that explaining it wasn't needed.

**Comment by zlainsama** [comment]
I'm sorry about the late reply.
What goal do you need to achieve?
Sorry about those text walls, it would be better to explain them with pictures and examples... but I was lazy.

**Comment by JadianRadiator** [comment]
I need to understand how to properly config PeacefulSurface so that I don't have to ask for help every time I want to make a change..
And I've been refusing to make a decision on what to set it up for until I understand _how_ to set it up.

But since you asked....
No monsters at night above the level of new/blood moon.
Unless thundering and/or unlit at night level of darkness.
No monsters indoors.
Unless at unoccupied level of darkness, away from soft/natural lighting the area next to a window.

**Comment by zlainsama** [comment]
I added an new page: [Explanation for DefaultRule.json](https://github.com/zlainsama/PeacefulSurface/wiki/Explanation-for-DefaultRule.json)
Please let me know if you have any parts you don't understand.
