### ISSUE TITLE
Another Difficulty with configs

### ISSUE THREAD

**Issue by HoodBlah** [zlainsama/PeacefulSurface#38]
I am trying to make it so that no hostile mobs spawn at all. But I still want them to spawn from other means (eggs, spawners, etc.).

I am trying to use the altitude to do this and it worked in 1.19.2 but not in 1.20.1.

{
  "Disabled": false,
  "Living": false,
  "Monster": true,
  "Animal": false,
  "UseMobFilter": true,
  "UseDimensionFilter": true,
  "UseBiomeFilter": false,
  "Checking_LightLevel": false,
  "Checking_Altitude": true,
  "Checking_BlockLight": false,
  "Checking_SkyLight": false,
  "Sunny": false,
  "Raining": false,
  "Thundering": false,
  "Day": false,
  "Night": false,
  "InvertedMobFilter": false,
  "InvertedDimensionFilter": false,
  "InvertedBiomeFilter": true,
  "InvertedLightLevelChecking": false,
  "InvertedAltitudeChecking": false,
  "InvertedBlockLightChecking": false,
  "InvertedSkyLightChecking": false,
  "mobFilter": "(\\bminecraft:slime\\b)",
  "dimensionFilter": "(\\bminecraft:the_end\\b)|(\\bminecraft:the_nether\\b)",
  "biomeFilter": "(\\bminecraft:plains\\b)",
  "LightLevel": 0,
  "Altitude": -100,
  "BlockLight": 0,
  "SkyLight": 0,
  "MoonPhase": 0,
  "DisabledUnderBloodmoon": false,
  "DisabledWhenSunny": false,
  "DisabledWhenRaining": false,
  "DisabledWhenThundering": false,
  "DisabledWhenDay": false,
  "DisabledWhenNight": false
}

**Comment by zlainsama** [comment]
Your config looks right, let me do some test. Which modloader are you using?

**Comment by HoodBlah** [comment]
Forge

**Comment by zlainsama** [comment]
Your config works on my end, with only PeacefulSurface installed.
What mobs are spawning?

**Comment by HoodBlah** [comment]
All vanilla mobs and a couple modded ones from creeper and enderman overhaul.

**Comment by zlainsama** [comment]
Can you share your modlist?

**Comment by HoodBlah** [comment]
[Ex.zip](https://github.com/zlainsama/PeacefulSurface/files/13710315/Ex.zip)

**Comment by zlainsama** [comment]
Your setup works on my end, no hostile mobs are spawning naturally.
Were you editing the config in game? did you saved the file and used command '/reloadpeace'?

**Comment by HoodBlah** [comment]
I’ve closed and reopened the game but I never used that command. I also see from your screenshot that you are on the surface. I was in a cave around level 6 and I had zombies and stuff spawning. Can you go underground and check if they are spawning?

**Comment by zlainsama** [comment]
You don't need that command if you have restarted the game.
The setup works on my end...

![image](https://github.com/zlainsama/PeacefulSurface/assets/3251859/5fc53cdc-6bda-4049-b5e4-97b0b3602c24)

**Comment by zlainsama** [comment]
What launcher are you using?

**Comment by HoodBlah** [comment]
That is strange. I am using prism launcher but does that really matter?

**Comment by zlainsama** [comment]
As you can see in that screenshot, only ambient mobs (bats) are spawning.
And out of screen, there are slimes, but those are excluded as specified in the config.
Some launchers do have modified some game code in the past, not sure now. I'm using the CurseForge launcher.

**Comment by HoodBlah** [comment]
I redid the steps and now everything is working. I do not know why it wasn’t working in the beginning but it is now lol. Thank you very much for you help and I’m sorry for wasting your time!

**Comment by zlainsama** [comment]
Don't forget to delete the link to your modlist.
