### ISSUE TITLE
Separate configs per game difficulty

### ISSUE THREAD

**Issue by TheDeviantCrafter** [zlainsama/PeacefulSurface#39]
I would like to configure the mod to only disable mob spawns on easy difficulty. Is that possible?

**Comment by zlainsama** [comment]
Currently, this mod does not have options for difficulty detection, so, no.
Do you need this?

**Comment by zlainsama** [comment]
Which version and loader are you working on? I will get a version out with difficulty filter.
And I think there are other similar mods that already do these, but I'm not sure.

**Comment by TheDeviantCrafter** [comment]
Forge 1.20.1

I think Apathetic Mobs has a difficulty filter, but it's still on 1.19.

**Comment by zlainsama** [comment]
Implemented in 1.20.1-v2, 1.20.2-v2, 1.20.4-v2, 1.20.1-v2-fabric, 1.20.2-v2-fabric, 1.20.4-v2-fabric, 1.20.2-v2-neoforge and 1.20.4-v2-neoforge.

**Comment by TheDeviantCrafter** [comment]
I can't get this to work. Setting difficulty to 1 in the config causes hostile mobs to spawn in the surface on all difficulty levels except peaceful.

This is my config: https://gist.github.com/TheDeviantCrafter/8b76d4f8e25f4d382de191e2a4f5dc7b

It is a default generated rule in the latest version, but with difficulty set to 1 and the biome filter empty.

**Comment by TheDeviantCrafter** [comment]
Setting `"Difficulty": 0` still works as intended. Mobs stop spawning on the surface on all difficulties.

**Comment by zlainsama** [comment]
It is working as intended, exactly as this issue's title described.
You need multiple rule files for each difficulty.
The Difficulty value make the rule itself only work in that difficulty.
