### ISSUE TITLE
Help with configuration to allow mob spawning during full moon

### ISSUE THREAD

**Issue by johalun** [zlainsama/PeacefulSurface#41]
Hi!

So, for allowing mobs to spawn during a single moon phase, do I have to create one config for each of the other phases and disallow spawning, or can I create one for just the phase I want (full moon), and allow spawning there?

Thanks!

**Comment by zlainsama** [comment]
In current implementation, you need to create one config for each of the other moon phases disabling spawning during them... sorry about the inconvenience.
