### ISSUE TITLE
Help with configuration.

### ISSUE THREAD

**Issue by Bayrat** [zlainsama/PeacefulSurface#42]
So I wanted to configure the mod so that monsters only spawn during certain phases of the moon (phases 5 through 8) And disabling monster spawning entirely day outside of those specific nights. However, my configuration doesn't appear to be working as monsters still spawn normally. This is what my config looks like:

{
  "Disabled": false,
  "Living": false,
  "Monster": true,
  "Animal": false,
  "UseMobFilter": true,
  "UseDimensionFilter": true,
  "UseBiomeFilter": false,
  "Checking_LightLevel": false,
  "Checking_Altitude": true,
  "Checking_BlockLight": false,
  "Checking_SkyLight": false,
  "Sunny": false,
  "Raining": false,
  "Thundering": false,
  "Day": true,
  "Night": true,
  "InvertedMobFilter": false,
  "InvertedDimensionFilter": false,
  "InvertedBiomeFilter": true,
  "InvertedLightLevelChecking": false,
  "InvertedAltitudeChecking": true,
  "InvertedBlockLightChecking": false,
  "InvertedSkyLightChecking": false,
  "mobFilter": "(\\bminecraft:slime\\b)",
  "dimensionFilter": "(\\bminecraft:the_end\\b)|(\\bminecraft:the_nether\\b)",
  "biomeFilter": "(\\bminecraft:plains\\b)",
  "LightLevel": 0,
  "Altitude": 300,
  "BlockLight": 0,
  "SkyLight": 0,
  "MoonPhase": 1,
  "MoonPhase": 2,
  "MoonPhase": 3,
  "MoonPhase": 4,   
  "Difficulty": 0,
  "DisabledUnderBloodmoon": true,
  "DisabledWhenSunny": false,
  "DisabledWhenRaining": false,
  "DisabledWhenThundering": false,
  "DisabledWhenDay": false,
  "DisabledWhenNight": false
}

**Comment by zlainsama** [comment]
You can't have multiple MoonPhase entries in one rule file.
You need to duplicate this rule file for each of the moon phases that you don't want monsters, you can just name them like rule1.json rule2.json and so on.

**Comment by Bayrat** [comment]
Ah okay thanks!
