### ISSUE TITLE
Allow spawns during blood moon is broken since Enhanced Celestials update

### ISSUE THREAD

**Issue by johalun** [zlainsama/PeacefulSurface#43]
Since Enhanced Celestials 5.0.2.2 (or probably 5.0.2.0 I think), allowing spawns during blood moon with the option `"DisabledUnderBloodmoon": true` is broken.

With Enhanced Celestials 5.0.1.0 mobs would spawn like expected during blood mooon, after the update we only see enderman spawning. We have whitelisted enderman so they spawn every night, however during blood moon they spawn in crazy amounts, but no other mobs, kind of like every other mob type was replaced by an enderman. 

Minecraft 1.20.1
Forge 43.7.10
peacefulsurface-1.20.1-v2.jar

If I remove peaceful surface (or downgrade Enhanced Celestials to 5.0.1.0) everything works as expected so my guess is that this mod is not handling lunar events correctly since Enhanced Celestial 5.0.2.0. 

There's a discussion going about this on over at #enhanced-celestials on Corgi's discord.

**Comment by johalun** [comment]
Wow that was fast. Thank you :)

**Comment by zlainsama** [comment]
I often don't check things for days, it just happen to coincide with your report :)
However, I didn't check the patch in game, please let me know if it doesn't work.

**Comment by johalun** [comment]
I'll check as soon as it's up on CF.

**Comment by johalun** [comment]
I've tested with latest versions of both mods and it seems to work again now. Thanks again for fixing it so quickly!
