### ISSUE TITLE
Not working with Advent of Ascension?

### ISSUE THREAD

**Issue by MechanosG** [zlainsama/PeacefulSurface#5]
Wanted to use Peaceful Surface to override the hostile spawns so they only spawn once light level is under a certain amount, in the overworld.  It seems to not be affecting their spawns however.  Is this an incompatibility, or is my config not setup correctly?  This is the config I'm using in DefaultRule.json.

{
  "Disabled": false,
  "Living": false,
  "Mob": true,
  "Animal": false,
  "Tameable": false,
  "Checking_LightLevel": true,
  "Raining": false,
  "Thundering": false,
  "Day": false,
  "Night": false,
  "InvertedMobFilter": false,
  "InvertedDimensionFilter": true,
  "InvertedLightLevelChecking": false,
  "mobFilter": "(\bSlime\b)",
  "dimensionFilter": "(\bOverworld\b)",
  "LightLevel": 1
}

I've also tried changing "(\bOverworld\b)" to "(\bDIM0\b)" and "DIM0".

**Comment by zlainsama** [comment]
Which version of Advent of Ascension are you using? where can I get it? I will look into it if I can find it.

**Comment by MechanosG** [comment]
Using AoA-2.3.13 which comes with FTB Modpack Departed version 1.2.1.
I'll probably update to 2.4.5 or 2.4.B sooner than later though.  Didn't know they were out.
Also just cuz I forgot to mention it, using the latest PeacefulSurface-1.7.x-v7.jar.

**Comment by zlainsama** [comment]
PeacefulSurface should work with AoA, at least in AoA-2.4.B.
You should check if it is working with normal mobs, to see if there is any incompatibilities in mob spawning.

**Comment by MechanosG** [comment]
So I set the light level to 15, which in theory, should make vanilla mobs start spawning all over right?  Wasn't working at all.  Not a single vanilla mob in sight.  I really have no idea why it's not working.  I even set dimension filters back to default and it still didn't do anything.

**Comment by zlainsama** [comment]
No, this mod acts as a filter to mob spawning, which means it will not force the mob to spawn beyond it's normal limit.
You should delete the json file and let the mod generate a default one, test to see if it stops mobs from spawning on surface in night time. If they still spawn, then there's some incompatibilities with your other mods.

**Comment by MechanosG** [comment]
I know this is over a year old now.  But noticed it was recently closed.  Back in the day when I was messing with it, I never could get PeacefulSurface to stop AoA's mob spawning, even with other mods removed.  Dunno if that's still the case today, but figured I'd leave the comment.

**Comment by zlainsama** [comment]
I think AoA is using it's owning spawning system, thats why PeacefulSurface cannot do anything about that.
